apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    version: 1
    editable: true
    isDefault: false
  - name: Alertmanager
    type: alertmanager
    url: http://alertmanager:9093
    access: proxy
    jsonData:
      implementation: 'prometheus' 
    basicAuth: false
    #basicAuthUser: my_user
    #basicAuthPassword: test_password
