# https://prometheus.io/docs/alerting/latest/notification_examples/
# https://rtfm.co.ua/en/prometheus-alertmanagers-alerts-receivers-and-routing-based-on-severity-level-and-tags/
global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/XXXXXXX/XXXXXXX/XXXXXXXXXXXXXX'

route:
  # https://www.robustperception.io/whats-the-difference-between-group_interval-group_wait-and-repeat_interval
  group_by: ['alertname', 'cluster', 'job', 'environment', 'severity']
  repeat_interval: 24h
  group_interval: 5m
  # capture All Dev + All INFO
  receiver: 'warning'
  routes:
    # capture All WARN to the 'warning' with P3
    - match:
        alertname: debug_instance_hard_disk_low
      receiver: rb-slack
    - match:
        severity: warning
      receiver: warning
      routes:
      # forward Dev WARN to the 'default'
      - match_re:
          environment: .*(-dev).*
        receiver: default
      - match_re:
          alertname: .*(hard_disk).*
        receiver: rb-slack

    # capture All CRIT to the 'critical' with P1
    - match:
        severity: critical
      receiver: critical
      routes:
      # forward Stage CRIT to the 'warning'
      - match_re:
          environment: .*(-stage).*
        receiver: warning
      # forward Dev CRIT to the 'default'
      - match_re:
          environment: .*(-dev).*
        receiver: default

receivers:
  - name: 'default'
    slack_configs:
      - send_resolved: true
        title: '{{ if eq .Status "firing" }}:confused:{{ else }}:sunglasses:{{ end }} [{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }} (default)'
        text: "{{ range .Alerts }}*Priority*: `{{ .Labels.severity | toUpper }}`\nMonitoring host: {{ .Labels.monitor }}\n{{ .Annotations.description }}\n{{ end }}"

  # host alerts
  - name: 'warning'
    slack_configs:
      - send_resolved: true
        channel: "#notifications"
        title_link: 'http://alertmanager.homedns.xyz/prometheus/alerts'
        title: '{{ if eq .Status "firing" }}:flushed:{{ else }}:sunglasses:{{ end }} [{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }} (catchall)'
        text: "{{ range .Alerts }}*Priority*: `{{ .Labels.severity | toUpper }}`\nTarget: {{ .Labels.instance }}\n{{ .Annotations.description }}\n{{ end }}"

  - name: 'critical'
    slack_configs:
      - send_resolved: true
        title_link: 'http://alertmanager.homedns.xyz/prometheus/alerts'
        title: '{{ if eq .Status "firing" }}:scream:{{ else }}:sunglasses:{{ end }} [{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }}'
        text: "{{ range .Alerts }}*Priority*: `{{ .Labels.severity | toUpper }}`\n*Description*: {{ .Annotations.description }}\n{{ end }}"

  - name: 'debug'
    slack_configs:
      - send_resolved: true
        title_link: 'http://alertmanager.homedns.xyz/#/alerts'
        title: '{{ if eq .Status "firing" }}:sadparrot:{{ else }}:fastparrot:{{ end }} [{{ .Status | toUpper }}] {{ .CommonAnnotations.title }} (instances)'
        channel: '#system_events'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            *Description:* {{ .Annotations.description }}
            *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:>
            *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
        username: 'AlertManager'
        icon_emoji: ':prometheus:'
        #api_url: '__SLACK_WEBHOOK_URL__'

  - name: 'basic-slack'
    slack_configs:
      - send_resolved: true
        title_link: 'http://alertmanager.homedns.xyz/prometheus/alerts'
        title: '{{ if eq .Status "firing" }}:flushed:{{ else }}:sunglasses:{{ end }} [{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }} (catchall)'
        text: "{{ range .Alerts }}*Priority*: `{{ .Labels.severity | toUpper }}`\nMonitoring host: {{ .Labels.monitor }}\n{{ .Annotations.description }}\n{{ end }}"

  - name: 'rb-slack'
    slack_configs:
      - send_resolved: true
        channel: "#notifications"
        title_link: 'http://alertmanager.homedns.xyz/prometheus/alerts'
        title: '{{ if eq .Status "firing" }}:flushed:{{ else }}:sunglasses:{{ end }} [{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }} (rb-slack)'
        text: "{{ range .Alerts }}*Priority*: `{{ .Labels.severity | toUpper }}`\nTarget: {{ .Labels.instance }}\n{{ .Annotations.description }}\n{{ end }}"

